package com.deliverycore.after.model.audit.enums;

public enum AuditLogAction {

    ORDER_CREATED,
    ORDER_ACCEPTED,
    ORDER_STARTED,
    ORDER_DELIVERED,
    ORDER_CANCELED,

    PAYMENT_CREATED,
    PAYMENT_CONFIRMED,
    PAYMENT_REFUNDED,
    PAYMENT_FAILED,
    PAYMENT_EXPIRED,

    DELIVERYMAN_VERIFICATION_REQUESTED,
    DELIVERYMAN_APPROVED,
    DELIVERYMAN_REJECTED,
    DELIVERYMAN_SUSPENDED
}